### ISSUE TITLE
Markdown Format bar bug

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Outliner#49]
![Peek 2020-05-31 11-08](https://user-images.githubusercontent.com/13304792/83349782-58649a80-a32f-11ea-92a8-c7001bac665d.gif)

**Comment by phase1geo** [comment]
The button states are not working as I would expect them to. I'll get that fixed.

In Markdown mode, the buttons are only there to add formatting syntax. I'm not planning on having them remove the formatting (unlike non-Markdown formatting).

**Comment by wada3n** [comment]
Well, what do you think if completely delete this bar, the feature is related to the keyboard and the Markdown’s emphasis markups can be inserted directly
Instead, You can switch between Markdown mode and Rich Text mode from menu Format > Convert to Markdown or Format > Convert to Rich Text.

Markdown is applied directly to the text if the feature is activated. And turn into markups in the disable mode.
You will be better in my opinion

**Comment by phase1geo** [comment]
I have removed the formatting buttons from the bar in the development branch.  I have not added code for converting the text whenever the mode changes.  I'm not sure if I'm going to do this for the next release or not. If it doesn't go into the next stable release, it most likely will in the next.

**Comment by jaslar** [comment]
The behavior seems backward. In the devel branch, the markdown formatting bar shows only when enable Markdown formatting is DE-selected from preferences.

**Comment by phase1geo** [comment]
In Markdown mode, we are not displaying any formatting buttons in the format bar since you can format text with the Markdown syntax.  When Markdown mode is disabled, we display the formatting bar with all of the formatting options since in that mode, formatting is accomplished via rich text formatting-like options.

Eventually, I may take another stab at adding formatting options for Markdown, but I won't be doing this for the upcoming release.
