### ISSUE TITLE
Failed to build locally

### ISSUE THREAD

**Issue by waldyrious** [phase1geo/Outliner#5]
Following the instructions from the README:

```
$ git clone https://github.com/phase1geo/Outliner
...

$ cd Outliner/

$ ./app install-deps
...
The following additional packages will be installed:
  gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 libjavascriptcoregtk-4.0-18
  libjavascriptcoregtk-4.0-dev libmarkdown2 libsoup2.4-dev libwebkit2gtk-4.0-37 libxml2
Suggested packages:
  libsoup2.4-doc
The following NEW packages will be installed:
  gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 libjavascriptcoregtk-4.0-dev libmarkdown2
  libmarkdown2-dev libsoup2.4-dev libwebkit2gtk-4.0-dev libxml2-dev
The following packages will be upgraded:
  libjavascriptcoregtk-4.0-18 libwebkit2gtk-4.0-37 libxml2
...

$ ./app install
The Meson build system
Version: 0.53.0
Source dir: /home/waldyrious/repos/Outliner
Build dir: /home/waldyrious/repos/Outliner/build
Build type: native build
Project name: com.github.phase1geo.outliner
Project version: 1.0.1
C compiler for the host machine: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
C linker for the host machine: cc GNU ld.bfd 2.33.1
Vala compiler for the host machine: valac (valac 0.40.18)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /home/waldyrious/.linuxbrew/bin/pkg-config (0.29.2)
WARNING: Could not detect glib version, assuming 2.54. You may get build errors if your glib is older.
Configuring config.h using configuration
Found pkg-config: /home/waldyrious/.linuxbrew/bin/pkg-config (0.29.2)
Found CMake: /home/waldyrious/.linuxbrew/bin/cmake (3.16.2)
Run-time dependency gtk+-3.0 found: NO (tried pkgconfig and cmake)

meson.build:36:0: ERROR: Dependency "gtk+-3.0" not found, tried pkgconfig and cmake

A full log can be found at /home/waldyrious/repos/Outliner/build/meson-logs/meson-log.txt
Unable to initialize, please review log
```

Could this be caused by missing dependencies in the `install-deps` script?

**Comment by phase1geo** [comment]
I will look into this and see if I can figure it out. You should be able to manually install the dependencies listed in the README to get you going in the meantime (if you haven’t done this already).

**Comment by phase1geo** [comment]
Everything seems to be working properly in my environment. What distribution are you attempting to build from?

**Comment by waldyrious** [comment]
> You should be able to manually install the dependencies listed in the README to get you going in the meantime (if you haven’t done this already).

I didn't do it manually on purpose, to help with debugging this issue.

> What distribution are you attempting to build from?

I'm on elementaryOS 5.1 Hera.

**Comment by phase1geo** [comment]
Well that is strange. I will admit that the app script is one that I got from someone else so I don’t know exactly how install-deps works. I will try to do some more debugging by setting up a clean elementary OS virtual machine.

**Comment by phase1geo** [comment]
I'm stumped. I installed elementary OS Hera in a brand new virtual machine, installed dpkg-dev so that the dpkg-checkbuilddeps was available, ran './app install-deps', and I was able to get Outliner compiled without further issue.

Here is the important part of the output after running './app install-deps'. Notice that libgtk-3-dev is getting installed as part of this process (this was the library that your environment seems to be missing):

trevorw@trevorw-VirtualBox:~/Downloads/Outliner-master$ ./app install-deps
sudo apt install meson valac debhelper libcairo2-dev libgranite-dev libgtk-3-dev libxml2-dev libwebkit2gtk-4.0-dev libmarkdown2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gir1.2-vte-2.91 libido3-0.1-0
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  autoconf automake autopoint autotools-dev dh-autoreconf dh-strip-nondeterminism gir1.2-gee-0.8 gir1.2-granite-1.0
  gir1.2-harfbuzz-0.0 gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 icu-devtools libarchive-cpio-perl
  libatk-bridge2.0-dev libatk1.0-dev libatspi2.0-dev libcairo-script-interpreter2 libdbus-1-dev libdrm-amdgpu1
  libdrm-common libdrm-dev libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libegl1-mesa-dev libepoxy-dev
  libexpat1-dev libfile-stripnondeterminism-perl libfontconfig1-dev libfreetype6-dev libgdk-pixbuf2.0-dev
  libgee-0.8-dev libgles1 libglib2.0-dev libglib2.0-dev-bin libglvnd-core-dev libglvnd-dev libgraphite2-dev
  libharfbuzz-dev libharfbuzz-gobject0 libice-dev libicu-dev libicu-le-hb-dev libicu-le-hb0 libicu60 libiculx60
  libjavascriptcoregtk-4.0-18 libjavascriptcoregtk-4.0-dev libltdl-dev libmail-sendmail-perl libmarkdown2 libopengl0
  libpango1.0-dev libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libpixman-1-dev libpng-dev libpng-tools
  libpthread-stubs0-dev libsigsegv2 libsm-dev libsoup2.4-dev libsys-hostname-long-perl libtool libvala-0.40-0
  libwayland-bin libwayland-client0 libwayland-cursor0 libwayland-dev libwayland-egl1 libwayland-server0
  libwebkit2gtk-4.0-37 libx11-dev libx11-doc libx11-xcb-dev libxau-dev libxcb-dri2-0-dev libxcb-dri3-dev
  libxcb-glx0-dev libxcb-present-dev libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-shm0-dev
  libxcb-sync-dev libxcb-xfixes0-dev libxcb1-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev
  libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbcommon-dev libxml2 libxrandr-dev libxrender-dev
  libxshmfence-dev libxtst-dev libxxf86vm-dev m4 mesa-common-dev ninja-build pkg-config po-debconf python3-distutils
  python3-lib2to3 valac-0.40-vapi wayland-protocols x11proto-composite-dev x11proto-core-dev x11proto-damage-dev
  x11proto-dev x11proto-fixes-dev x11proto-input-dev x11proto-randr-dev x11proto-record-dev x11proto-xext-dev
  x11proto-xf86vidmode-dev x11proto-xinerama-dev xorg-sgml-doctools xtrans-dev zlib1g-dev
Suggested packages:
  autoconf-archive gnu-standards autoconf-doc dh-make dwz libcairo2-doc libglib2.0-doc libgraphite2-utils libgtk-3-doc
  libice-doc icu-doc libtool-doc libpango1.0-doc libsm-doc libsoup2.4-doc gfortran | fortran95-compiler gcj-jdk
  libwayland-doc libxcb-doc libxext-doc m4-doc libmail-box-perl
The following NEW packages will be installed:
  autoconf automake autopoint autotools-dev debhelper dh-autoreconf dh-strip-nondeterminism gir1.2-gee-0.8
  gir1.2-granite-1.0 gir1.2-harfbuzz-0.0 gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 icu-devtools
  libarchive-cpio-perl libatk-bridge2.0-dev libatk1.0-dev libatspi2.0-dev libcairo-script-interpreter2 libcairo2-dev
  libdbus-1-dev libdrm-dev libegl1-mesa-dev libepoxy-dev libexpat1-dev libfile-stripnondeterminism-perl
  libfontconfig1-dev libfreetype6-dev libgdk-pixbuf2.0-dev libgee-0.8-dev libgles1 libglib2.0-dev libglib2.0-dev-bin
  libglvnd-core-dev libglvnd-dev libgranite-dev libgraphite2-dev libgtk-3-dev libharfbuzz-dev libharfbuzz-gobject0
  libice-dev libicu-dev libicu-le-hb-dev libicu-le-hb0 libiculx60 libjavascriptcoregtk-4.0-dev libltdl-dev
  libmail-sendmail-perl libmarkdown2 libmarkdown2-dev libopengl0 libpango1.0-dev libpcre16-3 libpcre3-dev libpcre32-3
  libpcrecpp0v5 libpixman-1-dev libpng-dev libpng-tools libpthread-stubs0-dev libsigsegv2 libsm-dev libsoup2.4-dev
  libsys-hostname-long-perl libtool libwayland-bin libwayland-dev libwebkit2gtk-4.0-dev libx11-dev libx11-doc
  libx11-xcb-dev libxau-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev libxcb-randr0-dev
  libxcb-render0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb1-dev libxcomposite-dev
  libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev
  libxkbcommon-dev libxml2-dev libxrandr-dev libxrender-dev libxshmfence-dev libxtst-dev libxxf86vm-dev m4
  mesa-common-dev meson ninja-build pkg-config po-debconf python3-distutils python3-lib2to3 valac valac-0.40-vapi
  wayland-protocols x11proto-composite-dev x11proto-core-dev x11proto-damage-dev x11proto-dev x11proto-fixes-dev
  x11proto-input-dev x11proto-randr-dev x11proto-record-dev x11proto-xext-dev x11proto-xf86vidmode-dev
  x11proto-xinerama-dev xorg-sgml-doctools xtrans-dev zlib1g-dev
The following packages will be upgraded:
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libicu60
  libjavascriptcoregtk-4.0-18 libvala-0.40-0 libwayland-client0 libwayland-cursor0 libwayland-egl1 libwayland-server0
  libwebkit2gtk-4.0-37 libxml2
15 upgraded, 124 newly installed, 0 to remove and 73 not upgraded.

**Comment by waldyrious** [comment]
Hmm... `libgtk-3-dev` is actually installed; I ran `sudo apt install libgtk-3-dev` and it said

> libgtk-3-dev is already the newest version (3.22.30-1ubuntu4).

I still get the same error

    Run-time dependency gtk+-3.0 found: NO (tried pkgconfig and cmake)

If I try to manually install all the dependencies from the readme, the output is:

```
...
The following additional packages will be installed:
  libvala-0.40.0
The following packages will be upgraded:
  libvala-0.40.0 valac
...
```

Does that make sense to you?

**Comment by waldyrious** [comment]
Hmmm... looks like this was caused by having `pkg-config` installed via Linuxbrew. I ran `brew uninstall pkg-config` and now the `./app install` command succeeds 🤷‍♂

Do you think there's anything the installation script could to do bypass that problem (or at least provide a more relevant error message)?

**Comment by phase1geo** [comment]
I'm not sure that I have any ideas on how to detect this type of problem. As such, I am not going to implement anything more than what currently exists. If you or someone else would like to provide a pull request with something that makes sense, I will consider integrating it. Though I'm not sure that this type of problem is one that a typical user would run into.

**Comment by waldyrious** [comment]
Yes, I agree. I have no idea how this could be avoided either. Maybe @sjackman could offer some insight regarding the issue with Linuxbrew's `pkg-config`?

Anyway, since the problem is resolved, I'll go ahead and close this issue for now; it will nevertheless serve as documentation should anyone come across the same problem.

**Comment by sjackman** [comment]
Homebrew's `pkg-config` only reports packages installed by Homebrew. You have two options:
1. `brew install gtk+`
2. Temporarily remove Homebrew from our `PATH` before installing Outliner with `PATH=/usr/bin:/bin`

**Comment by waldyrious** [comment]
Thanks for the clarification and helpful suggestions @sjackman!
