### ISSUE TITLE
Select multiple row to apply

### ISSUE THREAD

**Issue by vizelk** [phase1geo/Outliner#76]
Hello everyone,

Another beautiful program... Some request if you have time:

1/ an appimage to make it portable and use anywhere
2/ automatic style for each indent level
`ex: indent 0 : header 1, indent 1 : header 2...`
3/ ability to select multiple row, to apply style (header, font size, font color...)(for now I have to change style row by row)

Really nice program
Thanks phase1geo!

**Comment by phase1geo** [comment]
1. Outliner has a Flatpak manifest.  Flatpaks will be the way that elementary OS packages applications when elementary 6.0 is released.  There is no plans to support AppImage or Snaps.
2. Unlike Minder, Outliner doesn't support row/node styling.  Text can be formatted, but to accomplish that, text must be selected which can only occur when text is being edited.  You can only edit text one row at a time; therefore, support for text formatting is limited to one row at a time.  Additionally, Outliner doesn't support multi-row selections since it can complicate operations like row movement, deletion, etc.
